---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfig
data:
  username: root
  password: abcd@123!
...

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: secret-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret
  template:
    metadata:
      labels:
        app: secret
    spec:
      containers:
      - name: centos
        image: centos
        command: ["sleep", "10000"]
        env:
          - name: SECRET_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: username
        volumeMounts:
        - name: mycred
          mountPath: "/opt/foo"
          readOnly: true
      volumes:
      - name: mycred
        secret:
          secretName: mysecret
...