apiVersion: v1
kind: Pod
metadata:
  name: multi-pods 
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  - name: centos
    image: centos
    command: ["sleep", "10000"] 
