---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
...

---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - name: centos
    image: centos
    command: ["sleep", "12000"]
...