---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-rs
  template:
    metadata:
      labels:
        app: nginx-rs
    spec:
      containers:
      - name: nginx
        image: nginx:1.14
        ports:
        - containerPort: 80
...

---
kind: Service
apiVersion: v1
metadata:
  name: nginx-rs-svc
spec:
  selector:
    app: nginx-rs
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
...
